#! /bin/sh
# Inspired by https://github.com/cmur2/munin-openweather
# Steve Schnepp

# This part is taken from the original plugin
# Example usage:
#  Do
#    ln -s /path/to/openweather_ openweather_<query_string>
#  where <query_string> is either a search query "q_Paris" or
#  or an id search "id_2988507"
#
#  These parameters translate directly into a URL formed like this:
#    http://api.openweathermap.org/data/<api>/weather?<query_string>
#

query_string=$(printf '%s' "${0#*_}" | tr '_' '=')
TMPFILE=$(mktemp)
trap 'rm -f $TMPFILE' EXIT

graph_name=$(basename "$0")

# API returns temp in K, we have to convert it in F
KELVIN_BIAS=459.67
FARENHEIT_SCALE=1.8

curl -o "${TMPFILE}" -s "http://api.openweathermap.org/data/2.5/weather?mode=json&APPID=${api_key}&${query_string}"

CITY=$(jq -r '.name' "${TMPFILE}")

if [ "$1" = "config" ];
then
	cat <<- EOF
		multigraph ${graph_name}_temp
		graph_title temperature in ${CITY}
		graph_args --base 1000
		graph_vlabel F
		graph_category weather
		graph_info This graph shows the temperature in ${CITY}
		temp_avg.label avg
		temp_avg.cdef temp_avg,$FARENHEIT_SCALE,*,$KELVIN_BIAS,-

		multigraph ${graph_name}_humidity
		graph_title humidity in ${CITY}
		graph_args --base 1000 -l 0 -u 100
		graph_scale no
		graph_vlabel %
		graph_category weather
		graph_info This graph show the humidity in ${CITY}
		humidity.label humidity

		multigraph ${graph_name}_pressure
		graph_title pressure in ${CITY}
		graph_args --base 1000 -l 850 -u 1050 --rigid
		graph_scale no
		graph_vlabel hPa
		graph_category weather
		graph_info This graph show the pressure in ${CITY}
		pressure.label pressure

		multigraph ${graph_name}_wind_speed
		graph_title wind speed in ${CITY}
		graph_args --base 1000
		graph_vlabel m/s
		graph_category weather
		graph_info This graph show the wind speed in ${CITY}
		speed.label wind speed
	EOF

	# Continue if dirty config is enabled
	[ "$MUNIN_CAP_DIRTYCONFIG" = 1 ] || exit 0
fi

TEMP_AVG=$(jq -r '.main.temp' "${TMPFILE}")
TEMP_MIN=$(jq -r '.main.temp_min' "${TMPFILE}")
TEMP_MAX=$(jq -r '.main.temp_max' "${TMPFILE}")

HUMIDITY=$(jq -r '.main.humidity' "${TMPFILE}")
PRESSURE=$(jq -r '.main.pressure' "${TMPFILE}")

WD_SPEED=$(jq -r '.wind.speed' "${TMPFILE}")
WD_DIREC=$(jq -r '.wind.deg' "${TMPFILE}")

cat <<- EOF
	multigraph ${graph_name}_temp
	temp_avg.value	$TEMP_AVG

	multigraph ${graph_name}_humidity
	humidity.value $HUMIDITY

	multigraph ${graph_name}_pressure
	pressure.value $PRESSURE

	multigraph ${graph_name}_wind_speed
	speed.value $WD_SPEED
EOF


exit 0

: <<EOF
<?xml version="1.0" encoding="utf-8"?>
<current>
  <city id="2988507" name="Paris">
    <coord lon="2.35" lat="48.85"/>
    <country>FR</country>
    <sun rise="2015-01-01T07:43:52" set="2015-01-01T16:04:40"/>
  </city>
  <temperature value="275.099" min="275.099" max="275.099" unit="kelvin"/>
  <humidity value="100" unit="%"/>
  <pressure value="1038.33" unit="hPa"/>
  <wind>
    <speed value="2.46" name="Light breeze"/>
    <direction value="190.509" code="S" name="South"/>
  </wind>
  <clouds value="0" name="clear sky"/>
  <visibility/>
  <precipitation mode="no"/>
  <weather number="800" value="Sky is Clear" icon="01d"/>
  <lastupdate value="2015-01-01T11:42:50"/>
</current>
EOF
