#!/usr/bin/env python2
"""
munin US NOAA weather plugin (http://weather.noaa.gov)

Draws humidity in hPa.
Copy/link file as 'weather_humidity_CODE', like: weather_humidity_LOWW for Austria, Vienna.

Get the code by going to http://weather.noaa.gov, selecting your
location, and copying the code from the address bar of your browser; should
be something like CODE.html.

Linux users might need to adjust the shebang.
"""

import sys
import urllib
import re

url = 'http://weather.noaa.gov/pub/data/observations/metar/decoded/%s.TXT'

re_humidity = re.compile('Relative Humidity.*\s+(\d+)%')


code = sys.argv[0][(sys.argv[0].rfind('_')+1):]
if code == None: sys.exit(1)

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
  print "yes"

elif len(sys.argv) == 2 and sys.argv[1] == "config":
  print 'graph_title relative humidity at code %s' % code
  print 'graph_vlabel %'
  print 'graph_category weather'

  print 'humidity.label relative humidity'
  print 'humidity.type GAUGE'
  print 'graph_args --base 1000 -l 0 -u 100'
  print 'graph_scale no'

else:

  u = urllib.urlopen(url % code)
  txt = u.read()
  u.close()

  hPa = re_humidity.findall(txt)[0]

  print 'humidity.value %s' % hPa
