#!/usr/bin/env python2
"""
munin US NOAA weather plugin (http://weather.noaa.gov)

Draws temperature/dew point in F.
Copy/link file as 'weather_temp_CODE', like: weather_temp_LOWW for Austria, Vienna.

Get the code by going to http://weather.noaa.gov, selecting your
location, and copying the code from the address bar of your browser; should
be something like CODE.html.

Linux users might need to adjust the shebang.
"""

import sys
import urllib
import re

url = 'http://weather.noaa.gov/pub/data/observations/metar/decoded/%s.TXT'

re_F = re.compile('Temperature: (-?\d+\.?\d?) F \(')
re_DewF = re.compile('Dew Point: (-?\d+\.?\d?) F \(')

code = sys.argv[0][(sys.argv[0].rfind('_')+1):]
if code == None: sys.exit(1)

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
  print "yes"

elif len(sys.argv) == 2 and sys.argv[1] == "config":

  print 'graph_title temperature at %s' % code
  print 'graph_vlabel F'
  print 'graph_category weather'

  print 'temperature.label temperature'
  print 'dewpoint.label dew point'

  print 'graph_args --base 1000 -l 0'

else:

  u = urllib.urlopen(url % code)
  txt = u.read()
  u.close()

  F = re_F.findall(txt)[0]
  DewF = re_DewF.findall(txt)[0]

  print 'temperature.value %s' % F
  print 'dewpoint.value %s' % DewF

